{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $pullSecretName }}
  namespace: {{ $clusterName }}
stringData:
  .dockerconfigjson: '{{ index $.Values "pullSecret" | default "" }}' 
