{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set" $.Values.openshiftVersion }}
{{- $controlPlaneCount = $.Values.controlPlaneAgents | default 3 }}
{{- $workerCount = $.Values.workerAgents | default (($.Values.hosts | length) - $controlPlaneCount) }}

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ $clusterName }}
  namespace: {{ $clusterName }}
spec:
  platformType: BareMetal 
  clusterDeploymentRef:
    name: {{ $clusterName }}
  imageSetRef:
    name: {{ $imageSet }}
  {{- if not ($.Values.sno | default false) }}
  apiVip: {{ $.Values.apiVip }}
  ingressVip: {{ $.Values.ingressVip }}
  mastersSchedulable: {{ $.Values.mastersSchedulable | default false }}
  provisionRequirements:
    controlPlaneAgents: {{ $controlPlaneCount }}
    workerAgents: {{ $workerCount }}
  networking:
    clusterNetwork:
    - cidr: {{ $.Values.networking.clusterNetwork.cidr }}
      hostPrefix: {{ $.Values.networking.clusterNetwork.hostPrefix }}
    machineNetwork:
    - cidr: {{ $.Values.networking.machineNetwork.cidr }}
    serviceNetwork:
    {{- range $_, $network := $.Values.serviceNetwork }}
    - {{ $network }}
    {{ end }}
  {{- else }}
  networking:
    userManagedNetworking: true
  provisionRequirements:
    controlPlaneAgents: 1
  {{- end }}
  provisionRequirements:
  sshPublicKey: {{ $.Values.sshPublicKey | default "" }}
