{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
{{- range $_, $host := $.Values.hosts }}
{{- $hostname := (printf "%s.%s" ($host.name| trimSuffix $.Values.baseDomain) $.Values.baseDomain) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-%s" "bmc-credential" $hostname }}
  namespace: {{ $clusterName }}
data:
  username: {{ ($host.bmcUsername | default $.Values.bmcUsername) | b64enc }}
  password: {{ ($host.bmcPassword | default $.Values.bmcUsername) | b64enc }}
{{ end }}
