{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
{{- range $_, $host := $.Values.hosts }}
{{- $hostname := (printf "%s.%s" ($host.name| trimSuffix $.Values.baseDomain) $.Values.baseDomain) }}
{{- $bmcEndpoint := ($host.bmcEndpoint | default $.Values.bmcEndpoint) }}
{{- $bmcAddress := printf "%s%s%s" $.Values.bmcPrefix $host.bmcIP $bmcEndpoint }}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ $hostname }}
  namespace: {{ $clusterName }}
  annotations:
    bmac.agent-install.openshift.io/hostname: {{ $hostname }}
  labels:
    infraenvs.agent-install.openshift.io: {{ $clusterName }}
spec:
  automatedCleaningMode: disabled
  bmc:
    address: '{{ $bmcAddress }}'
    credentialsName: {{ printf "%s-%s" "bmc-credential" $hostname }}
    disableCertificateVerification: true
  bootMACAddress: '{{ $host.bootMACAddress }}'
  customDeploy:
    method: start_assisted_install
  online: true
{{ end }}
