apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: dcce-cle-oscp-bm-test-2
  namespace: dcce-cle-oscp-bm-test-2
  labels:
    cluster.open-cluster-management.io/clusterset: default
    hive.openshift.io/cluster-platform: agent-baremetal
spec:
  pullSecretRef:
    name: pullsecret-cluster-dcce-cle-oscp-bm-test-2
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          agentBareMetal-generated-infraenv-ai-flow: dcce-cle-oscp-bm-test-2-dcce-cle-oscp-bm-test-2
  baseDomain: va.gov
  clusterInstallRef:
    kind: AgentClusterInstall
    name: dcce-cle-oscp-bm-test-2
    group: extensions.hive.openshift.io
    version: v1beta1
  clusterName: dcce-cle-oscp-bm-test-2
  controlPlaneConfig:
    servingCertificates: {}
  installed: false

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: dcce-cle-oscp-bm-test-2
  namespace: dcce-cle-oscp-bm-test-2
spec:
  clusterDeploymentRef:
    name: dcce-cle-oscp-bm-test-2
  holdInstallation: true
  imageSetRef:
    name: img4.18.27-multi-appsub
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.30.0.0/16
    userManagedNetworking: false
  provisionRequirements:
    controlPlaneAgents: 3
  ingressVIP: 10.84.41.124
  apiVIP: 10.84.41.123
  apiVIPs:
    - 10.84.41.123

---
kind: Secret
apiVersion: v1
metadata:
  name: pullsecret-cluster-dcce-cle-oscp-bm-test-2
  namespace: dcce-cle-oscp-bm-test-2
  labels:
    agent-install.openshift.io/watch: 'true'
    cluster.open-cluster-management.io/backup: cluster
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzI5amJWOWhZMk5sYzNOZk1qSmxaRGRsWm1ZM00yVTRORFEwWXprM056TmpaV1UyWlRBeU5qazJOekE2Ums1TFdqZE5NRTFYUVVWS05EZFRTalJHVlVneFVWYzVTRVUxTjA1Vk5GSlBVVUUzUzBaYVdEQkNWRnBLTVVwUlRsRkVUa0l4U0ZGQlNFSlJOMFZCTVE9PSIsImVtYWlsIjoibWF0dGhldy5mdXF1YUB2YS5nb3YifSwicXVheS5pbyI6eyJhdXRoIjoiYjNCbGJuTm9hV1owTFhKbGJHVmhjMlV0WkdWMksyOWpiVjloWTJObGMzTmZNakpsWkRkbFptWTNNMlU0TkRRMFl6azNOek5qWldVMlpUQXlOamsyTnpBNlJrNUxXamROTUUxWFFVVktORGRUU2pSR1ZVZ3hVVmM1U0VVMU4wNVZORkpQVVVFM1MwWmFXREJDVkZwS01VcFJUbEZFVGtJeFNGRkJTRUpSTjBWQk1RPT0iLCJlbWFpbCI6Im1hdHRoZXcuZnVxdWFAdmEuZ292In0sInJlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbSI6eyJhdXRoIjoiZkhWb1l5MXdiMjlzTFdRd1ptWmlNRGd6TFRkbU56SXROR0U0TUMwNFl6Y3hMV1pqTTJFMVlqWmpPVGhtWWpwbGVVcG9Za2RqYVU5cFNsTlZlbFY0VFdsS09TNWxlVXA2WkZkSmFVOXBTbXBPYlZFeFRsZE9hRTFIV1RCT1JHc3dXVmRWZUZscVdURlpWRWsxVFdwYWJFNHlXbWhPYlZsM1RWTktPUzVYTUMxTVdHeHhXRTFHYzA1c1lYRllTalZhZEVwb1RVUkpSMU56WkV4T2MxZEpRazluWkhoQlFtTklZaTFRWnpWWFYySmFkbFZuYmsxZldtbEVZVkJtYmxWMldHNDViMGd6VmxSdk5GbHplWEp6ZW5rNWRXaGFiekUzVTJaYWN6QkxTRzlFWVdkU05qaHFhMjFCVFZCRE9WZG1hR0pWVTBoYVUybExabWgwYWkxRFZWVm1jR3d5VmtKVE0zbDRhM2d3ZFVKeE5WcGZSVkphVm5JeFlWaEtSMEpaZVRNd05WODViWGxJU0ZOcWJqbFVTV2xNVUdWT1lrbDVTSG93ZFRWdk5XNTBZVmhtYzFsMVptNU5RV1pQUlVSbGNuQmtOMFozVlZwd1lYbGlPRGRUVm1OUlZVUklkMUpxYURkNWNGaFdUbWg1U2taRGF6QjZlbTFRWVZGSVNXVjRRVWRPYW1GUk1IQTRhVTkyVlVVMVYyZG5hMHRqVWtGSk1HcHpkVVE1VTNveE5GUmFRWGh4Y2tVemNsY3dNMEpZUzBoSVdXMUhWakE1ZUZNNU1sSnFRVmRLZVVGUFdEVnJUbW90YXkxSWR6SkphMVZvWVZrNU5uVlFVVjg1UWxCcVVYSkJXbXB3WlVabGRYRllSek5rUms5NWNrSXRTVVI1ZDFsc1JETkxSMnRzTUVkVU9VWTFSVVJoYWpSbmRVMVpVbFpFT0VaWVVUTnFjeTFKTTNWVWFrMTFWMVo1UjBSaVdrTktUekZ3T0Vkc2VGcFJUMmx3Y1RKb1NHcGZjMko2YWt0VlpuTnFWMmt0ZUZkcU5GTjFNMHc1U1RJMVdGaGxZMVI2U0U1M1dGUklVRGxKYTA4eWVHRllia0ZuYjB0ck5UZHFiSE5KYm5kdlRuWmFVbEpuTkVveloxVktXV1pWYm5Kbk4wZE9WSEF6WjFaM01ERXhUV1JLVmtkUmRGcFdabEUwTFdKU1RVbExOM2x2VjNKSFFsWlVjemg0TWxBM1lpMVdibmhLVTFCd1kwcGtUMkZ0TmpONVRWcHdlRWxwZVhFMlIyaE9PRUp2Tm1kTldFSk9XRk4wV1dkMVJIbHVha0ZuY1ZnMWFGTnNhR1pQTkdSMmIzVkhNV1UwUWpkWWEwMHdTbVpyY1VOellWSjBhbEJhUXpabVF6QnNaamh2UW0xalgwTjJNVXAxVkdwV2NHaHJUUT09IiwiZW1haWwiOiJtYXR0aGV3LmZ1cXVhQHZhLmdvdiJ9LCJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6ImZIVm9ZeTF3YjI5c0xXUXdabVppTURnekxUZG1Oekl0TkdFNE1DMDRZemN4TFdaak0yRTFZalpqT1RobVlqcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU21wT2JWRXhUbGRPYUUxSFdUQk9SR3N3V1ZkVmVGbHFXVEZaVkVrMVRXcGFiRTR5V21oT2JWbDNUVk5LT1M1WE1DMU1XR3h4V0UxR2MwNXNZWEZZU2pWYWRFcG9UVVJKUjFOelpFeE9jMWRKUWs5blpIaEJRbU5JWWkxUVp6VlhWMkphZGxWbmJrMWZXbWxFWVZCbWJsVjJXRzQ1YjBnelZsUnZORmx6ZVhKemVuazVkV2hhYnpFM1UyWmFjekJMU0c5RVlXZFNOamhxYTIxQlRWQkRPVmRtYUdKVlUwaGFVMmxMWm1oMGFpMURWVlZtY0d3eVZrSlRNM2w0YTNnd2RVSnhOVnBmUlZKYVZuSXhZVmhLUjBKWmVUTXdOVjg1YlhsSVNGTnFiamxVU1dsTVVHVk9Za2w1U0hvd2RUVnZOVzUwWVZobWMxbDFabTVOUVdaUFJVUmxjbkJrTjBaM1ZWcHdZWGxpT0RkVFZtTlJWVVJJZDFKcWFEZDVjRmhXVG1oNVNrWkRhekI2ZW0xUVlWRklTV1Y0UVVkT2FtRlJNSEE0YVU5MlZVVTFWMmRuYTB0alVrRkpNR3B6ZFVRNVUzb3hORlJhUVhoeGNrVXpjbGN3TTBKWVMwaElXVzFIVmpBNWVGTTVNbEpxUVZkS2VVRlBXRFZyVG1vdGF5MUlkekpKYTFWb1lWazVOblZRVVY4NVFsQnFVWEpCV21wd1pVWmxkWEZZUnpOa1JrOTVja0l0U1VSNWQxbHNSRE5MUjJ0c01FZFVPVVkxUlVSaGFqUm5kVTFaVWxaRU9FWllVVE5xY3kxSk0zVlVhazExVjFaNVIwUmlXa05LVHpGd09FZHNlRnBSVDJsd2NUSm9TR3BmYzJKNmFrdFZabk5xVjJrdGVGZHFORk4xTTB3NVNUSTFXRmhsWTFSNlNFNTNXRlJJVURsSmEwOHllR0ZZYmtGbmIwdHJOVGRxYkhOSmJuZHZUblphVWxKbk5Fb3paMVZLV1daVmJuSm5OMGRPVkhBeloxWjNNREV4VFdSS1ZrZFJkRnBXWmxFMExXSlNUVWxMTjNsdlYzSkhRbFpVY3poNE1sQTNZaTFXYm5oS1UxQndZMHBrVDJGdE5qTjVUVnB3ZUVscGVYRTJSMmhPT0VKdk5tZE5XRUpPV0ZOMFdXZDFSSGx1YWtGbmNWZzFhRk5zYUdaUE5HUjJiM1ZITVdVMFFqZFlhMDB3U21acmNVTnpZVkowYWxCYVF6Wm1RekJzWmpodlFtMWpYME4yTVVwMVZHcFdjR2hyVFE9PSIsImVtYWlsIjoibWF0dGhldy5mdXF1YUB2YS5nb3YifX19
type: kubernetes.io/dockerconfigjson

---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: dcce-cle-oscp-bm-test-2
  labels:
    cloud: BareMetal
    cluster.open-cluster-management.io/clusterset: default
    feature.open-cluster-management.io/addon-application-manager: unreachable
    feature.open-cluster-management.io/addon-cert-policy-controller: unreachable
    feature.open-cluster-management.io/addon-cluster-proxy: unreachable
    feature.open-cluster-management.io/addon-config-policy-controller: unreachable
    feature.open-cluster-management.io/addon-governance-policy-framework: unreachable
    feature.open-cluster-management.io/addon-managed-serviceaccount: unreachable
    feature.open-cluster-management.io/addon-search-collector: unreachable
    feature.open-cluster-management.io/addon-work-manager: unreachable
    name: dcce-cle-oscp-bm-test-2
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  taints:
    - effect: NoSelect
      key: cluster.open-cluster-management.io/unreachable
      timeAdded: '2025-11-07T15:51:45Z'

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: dcce-cle-oscp-bm-test-2
  namespace: dcce-cle-oscp-bm-test-2
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  clusterName: dcce-cle-oscp-bm-test-2
  clusterNamespace: dcce-cle-oscp-bm-test-2
  policyController:
    enabled: true
  searchCollector:
    enabled: true