{{- range $_, $host := $.Values.hosts }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-%s" "bmc-credential" $host.name }}
  namespace: {{ $clusterName }}
data:
  username: {{ $host.bmcUsername }}
  password: {{ $host.bmcPassword }}
{{ end }}
